version: "3.9"
services:
  api:
    build: .
    container_name: {{project_name}}-flask
    env_file:
      - .env
    ports:
      - "8001:8000"
    depends_on:
      - db
    volumes:
      - ./:/app

  db:
    image: postgres:16
    container_name: {{project_name}}-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432"

