FROM node:20-alpine
WORKDIR /app
COPY package.json .
RUN npm install
RUN npm install
n .
rfile <<'EOF'
OF'
ot")).render(<App />);
>

events {}
http {
  server {
    l    l    l    l    l    l    l    l    l    l    l    l    l    l    l    l    l    l    l    l    l    l    l    l    l    l    l    l    l    l    l    l    l do    l    l    l    l    l    l    l    l    l    l    l    l    l    l    l    l    l    l    l    l    l    l    l    l  ke    l    l    l    l    l    l    l    l    l    l    l    l    l    l    l    l    l    l    l    l    l    l    l    l    l    l    l    l    l    l    l    l    l do    l    l    l    l    l    l    l    l    l    l    l    l    l    l    l    l    l    l    l    l    l    l    l    l  ke    l    l    l    l    l    l    l    l    l    l    l    l    l    l    l    l    l    l    l    l    l    l    l    l    l    l    l    l  ro    l    l    l    l    l    l    l    l    l    l    l    l    l    l    l    l    l    l    l    ject_name}}
AUTHOR={{author}}
CREATED_AT={{created_at}}
