import "./globals.css";

export const metadata = {
  title: "{{project_name}}",
  description: "Generated by project-forge"
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
